Remove unwrap/expect
dusk-network/kadcast pull request #116
Opened 2022-10-20 09:14 UTC by herr-seppia

This is a larger refactor that aims to make the library more stable by removing unwrap and expect.

* Change `Peer::new` to return Result
* Change `blake2` from `0.9` to `0.10`

Resolves #115

2022-10-20 12:26 UTC, ZER0 requested changes
Overall looks good, but there are few things needs to be addressed or discussed.

2022-10-20 12:26 UTC, ZER0 commented on src/lib.rs
> +            .map(|(height, nodes)| {
This also looks confusing to me, and there are too many nested things.

2022-10-20 12:26 UTC, ZER0 commented on src/peer.rs
> +        x.try_into().expect("compute_id length = K_ID_LEN_BYTES")
This also doesn't makes much sense to me, maybe we can go over in pairing.

2022-10-20 12:26 UTC, ZER0 commented on src/transport.rs
>                          if let Some(message) = to_process {
Since you're doing already a pattern here I would suggest to avoid `map_err` and just have a `match to_process`.

2022-10-20 12:26 UTC, ZER0 commented on src/transport/encoding/raptorq.rs
> +                ErrorKind::InvalidInput,
If you want to keep the `io::Error` here, you should use `ErrorKind::UnexpectedEof` instead.

2022-10-20 12:26 UTC, ZER0 commented on src/transport/encoding/raptorq/decoder.rs
> +                                .or_else(|| {
This is also looks a bit too nested.

2022-10-24 08:22 UTC, herr-seppia commented
Everything has been addressed as discussed

2022-10-24 08:23 UTC, merged